#! /bin/bash

year=$(date +%Y)

source_dirs="config examples misc src support tests utils"

files="LICENSE.txt CMakeLists.txt"

for dir in $source_dirs; do
  files="$files $(find $dir \
    -name LICENSE.txt -o \
    -name CMakeLists.txt -o \
    -name \*.cmake -o \
    -name \*.c -o \
    -name \*.cpp -o \
    -name \*.h -o \
    -name \*.hpp -o \
    -name \*.inl -o \
    -name \*.cmake.in -o \
    -name \*.mk.in -o \
    -name \*.h.in -o \
    -name \*.hpp.in \
  )"
done

name="Matthew J. Smith and Overkit contributors"

for file in $files; do
  if [ $(grep -c "$name" $file) -eq 0 ]; then
    echo "WARNING: File $file possibly missing license header."
  fi
done

for file in $files; do
  cp "$file" old_license_file
  sed -e "s/Copyright (c) [0-9]\{4\} $name/Copyright (c) $year $name/g" old_license_file > "$file"
done

rm -f old_license_file
