#! /bin/bash

year=$(date +%Y)

files=
files="$files $(find . -name LICENSE.txt)"
files="$files $(find . -name CMakeLists.txt)"
files="$files $(find config -name \*.cmake)"
files="$files $(find examples -name \*.c -o -name \*.cpp)"
files="$files $(find include -name \*.h)"
files="$files $(find ovk -name \*.c -o -name \*.cpp -o -name \*.h -o -name \*.inl)"
files="$files $(find tests -name \*.c -o -name \*.cpp)"
files="$files $(find support -name \*.c -o -name \*.cpp -o -name \*.h -o -name \*.inl)"
files="$files $(find utils -name \*.c -o -name \*.cpp -o -name \*.h -o -name \*.inl)"

name="Matthew J. Smith and Overkit contributors"

for file in $files; do
  cp "$file" old_license_file
  sed -e "s/Copyright (c) [0-9]\{4\} $name/Copyright (c) $year $name/g" old_license_file > "$file"
done

rm -f old_license_file
